require_relative 'bootstrap_ar'
connect_to 'development'

# Question.create( quiz_id: '60s', query: 'What British Invasion act had the song "When I Get Home"?', a: 'The Hollies', b: 'The Rolling Stones', c: 'The Beatles', d: 'The Dave Clark Five', correct_answer: 'The Beatles' )
# Question.create( quiz_id: '60s', query: 'What Monkee had writing credits on their debut album?', a: 'Davy Jones', b: 'Micky Dolenz', c: 'Peter Tork', d: 'Michael Nesmith', correct_answer: 'Michael Nesmith' )


question_list = [
  [ '90s', 'What is the last name of "Dream Boy-Dream Girl" singer Cynthia?', 'Stefani', 'Meyerhoff', 'Vallejo', 'Torres', 'Torres' ],
  [ '90s', 'What Georgia band released the album “The Southern Harmony and Musical Companion” in 1992?', 'The B-52s', 'Collective Soul', 'R.E.M.', 'The Black Crowes', 'The Black Crowes' ],
  [ '90s', 'What is singer/songwriter Desmond Childs real name?', 'Eugene Dixon', 'Andrew Wright', 'Desmond Cain', 'John Charles Barrett, Jr.', 'John Charles Barrett, Jr.' ],
  [ '90s', 'What name did producer Kenny "Dope" Gonzalez use when he recorded "The Bomb! (These Sounds Fall Into My Mind)"?', 'The Bucketheads', 'Club 69', 'Love, Inc', 'Faithless', 'The Bucketheads' ],
  [ '90s', 'Depeche Modes 1990 album was titled "Music For The ____" (fill in the blank)', 'People', 'Joneses', 'Others', 'Masses', 'Masses' ],
  [ '90s', 'What singer/actor married actress Jill Goodacre in 1994?', 'Jon Bon Jovi', 'Phil Collins', 'Lou Diamond Phillips', 'Harry Connick, Jr.', 'Harry Connick, Jr.' ],
  [ '90s', 'What rock band released the critically aclaimed album "Goo" in 1990?', 'Alice In Chains', 'Sonic Youth', 'Soundgarden', 'The Pixies', 'Sonic Youth' ],
  [ '90s', 'What Ohio Players song was sampled in DJ Jazzy Jeff & the Fresh Princes "Boom! Shake The Room"?', 'Fire', 'Funky Worm', 'Just Another Day', 'Love Rollercoaster', 'Funky Worm' ],
  [ '90s', 'In what year did Savage Garden have a #1 hit with "Truly Madly Deeply"?', '1992', '1998', '1990', '1995', '1998' ],
  [ '90s', 'What group appeared in the movie "The Meteor Man"?', 'Kris Kross', 'Another Bad Creation', 'Hanson', 'Bell Biv DeVoe', 'Another Bad Creation' ],
  [ '90s', 'Who formed a corporation in 1999 with Jerry Butler, Lloyd Price, and Ben E. King called "The 4 Kings of Rhythm & Blues"?', 'Eric Wright', 'Gene Chandler', 'James Brown', 'Ernie K. Doe', 'Gene Chandler' ],
  [ '90s', 'Who are the members of Australian group Savage Garden?', 'Johnny Crawford & Noel Hogan', 'Darren Hayes & Daniel Jones', 'Bruce Bark & Jimmy Arnold', 'Johnny Desmond & Andrew Fletcher', 'Darren Hayes & Daniel Jones' ],
  [ '90s', 'What is Tina Turners real name?', 'Annie Mae Bullock', 'Roberta Streeter', 'Virginia Patterson Hensley', 'Brogan Sykes', 'Annie Mae Bullock' ],
  [ '90s', 'What all-star group formed to benefit the Nordoff-Robbins Music Therapy Foundation?', 'The Bravo All Stars', 'Quad City DJs', 'Young Black Teenagers', 'The Detroit City Stars', 'The Bravo All Stars' ],
  [ '90s', 'What movie featured Madonnas hit "Ill Remember"?', 'Evita', 'A League Of Their Own', 'Whos That Girl', 'With Honors', 'With Honors' ],
  [ '90s', 'What Aerosmith song had the lines: "That kind of lovin. Yeah now Im never, never, never, never gonna be the same"', 'Crazy', 'Pink', 'Amazing', 'What It Takes', 'Crazy' ],
  [ '90s', 'What is rapper MC Hammers real name?', 'Marvin Lee Aday', 'Hugh Cregg', 'Stanley Burrell', 'Jack Whitis', 'Stanley Burrell' ],
  [ '90s', 'Which groups original name was Wildcountry?', 'The Oak Ridge Boys', 'Sugarland', 'Brooks & Dunn', 'Alabama', 'Alabama' ],
  [ '90s', 'What was the name of Weird Al Yankovics parody of The Presidents Of The USAs "Lump"?', 'Gump', 'Stump', 'Dump', 'Bump', 'Gump' ],
  [ '90s', 'From what 1990 movie did "Sooner Or Later (I Always Get My Man)" win a Best Original Song Academy Award?', 'Postcards From The Edge', 'Dick Tracy', 'Junior', 'The Bodyguard', 'Dick Tracy' ],
  [ '90s', 'What band sang that they "finally found the love of a lifetime"?', 'Firehouse', 'Manhattan Transfer', 'Basia', 'Wham!', 'Firehouse' ],
  [ '90s', 'For what song did Gordon Kennedy, Wayne Kirkpatrick & Tommy Sims win a Song of the Year (songwriting) Grammy Award in 1997?', 'Change The World', 'Because You Loved Me', 'Blue', 'Give Me One Reason', 'Change The World' ],
  [ '90s', 'From what country were the Cowboy Junkies from?', 'Canada', 'Australia', 'UK', 'Mexico', 'Canada' ],
  [ '90s', 'Which of the following is NOT the name of an NKOTB (New Kids On The Block) album?', 'Growing Up', 'New Kids On The Block', 'The Block', 'Step By Step', 'Growing Up' ],
  [ '90s', 'From what country did 1990s alternative band Silverchair hail from?', 'Australia', 'Ireland', 'UK', 'Canada', 'Australia' ],
  [ '90s', 'What country star sang in his 1990 song "Sometimes I thank God for unanswered prayers"?', 'Garth Brooks', 'George Strait', 'Travis Tritt', 'Toby Keith', 'Garth Brooks' ],
  [ '90s', 'Which Matchbox Twenty song has these lyrics: "Everyone here, knows everyone here is thinking about somebody else" ?', 'Back 2 Good', '3 AM', 'One Life To Live', 'Unwell', 'Back 2 Good' ],
  [ '90s', 'Which Seattle band sang these lyrics in a hit song: "Im diseased, I dont mind, Ill make you love me til the day you die"?', 'Soundgarden', 'Alice In Chains', 'Pearl Jam', 'Mudhoney', 'Mudhoney' ],
  [ '90s', 'What rap group consisted of members Cee-Lo, Big Gipp, Khujo and T-Mo?', 'The Goodie Mob', 'Cypress Hill', 'The Lox', 'Three 6 Mafia', 'The Goodie Mob' ],
  [ '90s', 'For what group was Perry Farrell the lead singer?', 'Porno For Pyros', 'Silverchair', 'Red Hot Chilli Peppers', 'Smashing Pumpkins', 'Porno For Pyros' ],
  [ '90s', 'What is Fatboy Slims real name?', 'John Jackson', 'Lewis Lea', 'Johnny Corley', 'Norman Cook', 'Norman Cook' ],
  [ '90s', 'What is U2 guitarist The Edges real name?', 'Dane Hale', 'Paul Hewson', 'Reginald Kenneth Dwight', 'Dave Evans', 'Dave Evans' ],
  [ '90s', 'Who won the Grammy Award for Best New Artist in 1996?', 'Hootie & The Blowfish', 'Joan Osborne', 'Alanis Morissette', 'Desmond Cain', 'Hootie & The Blowfish' ],
  [ '90s', 'Who was the Dixie Chicks lead singer before Natalie Maines?', 'Laura Lynch', 'Pam Tillis', 'Crystal McCain', 'Janie Fricke', 'Laura Lynch' ],
  [ '90s', 'What is Marc Anthonys real name?', 'Marco Flores', 'Marco Sanchez', 'Marco Gomez', 'Marco Antonio Muniz', 'Marco Antonio Muniz' ],
  [ '90s', 'What was the name of the huge R&B lineup of stars with the hit "U Will Know" in 1994-1995?', 'Artist Against Apartheid', 'The Ruff Ryders', 'The All-Stars', 'BMU(Black Men United)', 'BMU(Black Men United)' ],
  [ '90s', 'What are the names of Beach Boy Brian Wilson’s daughters? (both are musicians)', 'Carnie & Wendy', 'Annie & Billie', 'Michelle & Marie', 'Kim & Christie', 'Carnie & Wendy' ],
  [ '90s', 'What is Foxy Browns real name?', 'Regina Bowman', 'Roberta Streeter', 'Inga Marchand', 'Kimberly Jones', 'Inga Marchand' ],
  [ '90s', 'What is singer Sades real name?', 'Helen Folasade Adu', 'Friday Peterson', 'Eileen Regina Edwards', 'Eliza Brock', 'Helen Folasade Adu' ],
  [ '90s', 'What singer played Isabel in the movie "Music Of The Heart"?', 'Stevie Nicks', 'Gloria Estefan', 'Jennifer Lopez', 'Madonna', 'Gloria Estefan' ],
  [ '90s', 'What band recorded the controversial song "Cop Killer"?', 'Body Count', 'Red Hot Chilli Peppers', 'NWA', 'Naughty By Nature', 'Body Count' ],
  [ '90s', 'What was the hit collaboration between Roberta Flack and Maxi Priest?', 'Wild World', 'Set The Night To Music', 'That Girl', 'Close To You', 'Set The Night To Music' ],
  [ '90s', 'What is artist Daddy Yankees real name?', 'Raymon d Ayala', 'Christopher Fryman', 'John Deutschendorf', 'Declan MacManus', 'Raymon d Ayala' ],
  [ '90s', 'What was the name of the cat that appeared in Paula Abduls "Opposites Attract" video?', 'Kit Cat', 'DJ Jazzy Cat', 'Fly Cat', 'MC Skat Cat', 'MC Skat Cat' ],
  [ '90s', 'What was the name of Motley Crues 1991 greatest hits compilation?', 'Forty Seasons', 'Decade Of Decadence', 'Living After Midnight', 'Vault', 'Decade Of Decadence' ],
  [ '90s', 'What trio includes members originally from the Soviet Union, Japan, and Ohio?', 'Deee-Lite', 'Musical Youth', 'The Cover Girls', 'Stereo MCs', 'Deee-Lite' ],
  [ '90s', 'What Texas R&B singer was discovered by Quincy Jones and appeared in the movie "Graffiti Bridge"?', 'Ralph Tresvant', 'Keith Sweat', 'Babyface', 'Tevin Campbell', 'Tevin Campbell' ],
  [ '90s', 'What is rapper Snoop Doggs real name?', 'Marvin Lee Aday', 'Brandon Lyons', 'Kenneth Edmonds', 'Calvin Broaddus', 'Calvin Broaddus' ],
  [ '90s', 'What movie featured "All For Love" by Bryan Adams, Rod Stewart and Sting?', 'Braveheart', 'The Three Musketeers', 'A Night In Heaven', 'Don Juan DeMarco', 'The Three Musketeers' ],
  [ '90s', 'A.L.T. and the Lost Civilization had a hit with a rap version of what song?', 'La Bamba', 'Heartbreak Hotel', 'Tequila', 'Louie Louie', 'Tequila' ],
  [ '90s', 'What rap artist appeared in the movies "Set It Off" and "The Bone Collector"?', 'Rah Digga', 'Queen Latifah', 'Lil Kim', 'Foxy Brown', 'Queen Latifah' ],
  [ '90s', 'What group was Norman Cook a part of before his work as Fatboy Slim?', 'The Communards', 'Technotronic', 'Company B', 'Beats International', 'Beats International' ],
  [ '90s', 'What song is sampled in Ice Cubes "Check Yo Self"?', 'Genius Of Love', 'The Way We Were', 'Hooked On A Feeling', 'The Message', 'The Message' ],
  [ '90s', 'What Rob Zombie hit had the lyrics "Dig through the ditches; Burn through the witches" ?', 'What?', 'Dragula', 'American Witch', 'Living Dead Girl', 'Dragula' ],
  [ '90s', 'How many siblings did Michael Jackson have?', '10', '6', '8', '4', '8' ],
  [ '90s', 'Who played the record label executive Mr. White in the movie "That Thing You Do"?', 'Kevin Bacon', 'Woody Allen', 'Tom Hanks', 'Tom Cruise', 'Tom Hanks' ],
  [ '90s', 'What movie did rapper Biz Markie appear in?', 'Slacker', 'Three Kings', 'The Meteor Man', 'Austin Powers', 'The Meteor Man' ],
  [ '90s', 'Which Spice Girls hit has these lyrics: "Candle light and soul forever; A dream of you and me together"', 'Say Youll Be There', 'Wannabe', '2 Become 1', 'Spice Up Your Life', '2 Become 1' ],
  [ '90s', 'Who won the Grammy Award for Best New Artist in 1998?', 'Hanson', 'Erykah Badu', 'Paula Cole', 'Fiona Apple', 'Paula Cole' ],
  [ '90s', 'From what movie did "When You Believe" win a Best Original Song Academy Award?', 'Pocahontas', 'The Little Mermaid', 'The Prince Of Egypt', 'The Lion King', 'The Prince Of Egypt' ],
  [ '90s', 'The first three “CSI” shows used songs from what band as the theme music?', 'The Kinks', 'The Who', 'The Rolling Stones', 'Chicago', 'The Who' ],
  [ '90s', 'In what city was Michael Jackson born?', 'Jackson, Mississippi', 'Jasper, Alabama', 'Gary, Indiana', 'Bellingham, Washington', 'Gary, Indiana' ]
]
question_list.each do |quiz_id, query, a, b, c, d, correct_answer|
  Question.create( quiz_id: quiz_id, query: query, a: a, b: b, c: c, d: d, correct_answer: correct_answer )
end